import { Skill } from "./types";

export const PRESET_SKILLS: Skill[] = [
  {
    id: "welink-cli",
    name: "WeLink 每日工作同步",
    version: "1.0.0",
    description: "自动从WeLink CLI获取当日工作内容、会议、待办，AI自动分类导入",
    author: "official",
    command: "welink-cli today",
    defaultSchedule: "0 0 18 * * 1-5",
    outputType: "text",
    defaultImportType: "auto",
    useAI: true,
    tags: ["企业微信", "welink", "办公"],
    icon: "📅",
  },
  {
    id: "git-log",
    name: "Git 提交记录同步",
    version: "1.0.0",
    description: "自动获取当日Git提交记录作为工作成果",
    author: "official",
    command: "git log --since=\"midnight\" --oneline --no-merges",
    defaultSchedule: "0 0 20 * * *",
    outputType: "text",
    defaultImportType: "achievement",
    useAI: true,
    tags: ["git", "开发", "代码提交"],
    icon: "💻",
  },
  {
    id: "daily-note",
    name: "通用每日总结导入",
    version: "1.0.0",
    description: "通用文本导入，AI自动区分工作总结、待办、成果",
    author: "official",
    command: "echo \"请替换为你的CLI命令\"",
    defaultSchedule: "0 0 21 * * *",
    outputType: "text",
    defaultImportType: "auto",
    useAI: true,
    tags: ["通用", "总结"],
    icon: "📝",
  },
];
